### ISSUE TITLE
acorn-dns launch checklist

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn-dns#25]
### Development 
- [x] Finish coding acorn-dns functionality @cjellick 
- [x] Make non-release builds of acorn point at `staging-dns.acrn.io` instead of `dns.acrn.io` @cjellick 
- [x] Write Acornfile for acorn-dns that includes application and database. DB will be replaced with the "production" MariaDB acorn @cjellick 
- [x] Update MariaDB acorn to new syntax. Test it to ensure it works. Ensure we have a way to access the db directly to run queries @cloudnautique 
- [x] ~Fix environment variable setting in acorn so that they can be set from args @ibuildthecloud~ modified Acornfile so that this isn't a blocker
- [x] ~Fix `acorn push`, which doesn't work @cjellick or @ibuildthecloud~ It works

### AWS Infrastructure
- [x] Create Route53 zones `on-acorn.io` and `staging.on-acorn.io` @cloudnautique 
  - [x] Create NS records for these zone in cloudflare DNS @cjellick 
- [x] Deploy production k3s cluster managed by rancher with instanceProfiled capable of CRUDing records in the r53 zones @cloudnautique
- [x] Deploy cert-manager into prod cluster and do the necessary so that it can issue certs for `acrn.io`. We will ultimately need certs for `staging-dns.acrn.io` and `dns.acrn.io` @cloudnautique 

### Deployment Infra
- [x] Hook fleet up to prod cluster and hooked up to GitHub @cloudnautique @ibuildthecloud 
- [x] Publish working GitHub actions for `acorn-setup` and `acorn-login` @vincent99  
- [x] Write GitHub Action CI to build and push an acorn for acorn-dns @cjellick 
- [x] Write and open pull requests for the k8s yaml to deploy the acorn apps for both staging and production. Need the apps themselves and cert-manager `certificate` objects. Separate PRs for staging and production @cjellick  

### Go live
- [x] Review and merge staging fleet PR to deploy the staging instance of acorn-dns @ibuildthecloud @cloudnautique 
- [x] set default mode in acorn to `auto` (currently disabled by default) after the services are up and running @cjellick 
- [x] Smoke test against staging @cjellick 
- [x] Review and merge prod fleet PR to deploy production instance of acorn-dns @ibuildthecloud @cloudnautique 
- [x] Cut a pre-release of acorn @cjellick 
- [x] Smoke test against production @cjellick 

### Docs
- [x] Add content explaining acorn-dns and clusterDomains @cjellick
